### ISSUE TITLE
Configuration detects no Displays

### ISSUE THREAD

**Issue by Shazuli** [1Revenger1/NVCAP-Calculator#4]
***Hi***

![Screenshot 2021-06-20 at 15 31 50](https://user-images.githubusercontent.com/9884180/122676146-efbbba80-d1dc-11eb-855f-8ef5552602ec.png)

From the picture, you can see that it doesn't show any displays for some reason. I tried calculating the NVCAP by leaving this blank, and my system didn't crash on boot but I now only have one screen. I reverted back to before I tried the legacy Nvidia patching which gave me back my second screen. I tried running your program again both with and without the GPU patch, but they showed the exact same screen (no detected screens). No idea what's causing this, so maybe you have an idea?

I'm trying to patch a GTX660 with one HDMI Port and one Display Port display connected to it. Running Big Sur `11.4` on OpenCore `0.7.0`

**Comment by 1Revenger1** [comment]
It should've errored out with the GTX 660.
They changed where the DCB tables were in 500+ series cards so the program isn't able to extract the entries out of the firmware. In my experience though, Kepler doesn't require nvcap to be set usually.

I guess I can take a look again in my rust branch - that branch should also remove the nodejs dependency

**Comment by Shazuli** [comment]
Question:
You think a 970 card would work better @1Revenger1? This system has the 660 card, but my older system has a 970 I installed a while ago. I’d prefer having the 970 where it is and run with the 660 on this system (I use this system more for productivity and tinkering, and therefore don’t need a good graphics card while the second is for gaming and do need a faster card).
