### ISSUE TITLE
Unable to open

### ISSUE THREAD

**Issue by Mkkonecny** [1Revenger1/NVCAP-Calculator#5]
Hello first of all, I'm sorry for this stupid issue actually isn't an issue probs. I'm trying to use NVCAP but have no idea how to open it. Already spend 1 hour of googling and trying to find related info but there's just no explanation. Could you please help me out how can I open and use it? 

Thanks a lot and one more time I'm just really sorry...

**Comment by averycblack** [comment]
are you opening it in terminal? Need to open cmd/powershell on Windows, Terminal in macOS, or whichever terminal you use in Linux. Then navigate to the program and run it from there. Easiest way may be to just drag the program into your terminal if you don't know how to use it.

**Comment by Mkkonecny** [comment]
In Terminal on Mac, I would like to but actually don't know which file to drag there since nothing from the repo worked for me, nothing in src or cargo. Should I just drag the whole zip?! Or I'm doing it conpletely wrong? I'm used to GitHub the way that it's in some apps there's repo and under releases is an app which I download and work with it later. But don't know maybe I'm just stupid tho. Oh hold on this one should I drag to terminal? nvcap_calculator_macos_amd64 - doesn't matter if I'm using intel? 😁

**Comment by averycblack** [comment]
amd64 refers to any x86 64 bit machine basically, it's fine to use that.

**Comment by Mkkonecny** [comment]
Thanks a lot. I was unable to open it anyway but find out that I need to cd folder where it is and then Chloe +x ./nvcap after that I was able to run it. Thanks again!
