### ISSUE TITLE
Invalid DCB Signature

### ISSUE THREAD

**Issue by msakthiganesh** [1Revenger1/NVCAP-Calculator#8]
Hi,

I just installed macOS Big Sur using OpenCore and couldn't get my external monitor to be recognised. I have a NVIDIA Quadro K2100M Graphics Card. 

I downloaded the VGA Bios from here: https://www.techpowerup.com/vgabios/?did=10DE-11FC-103C-197B 

But I get `Invalid DCB Signature` while trying to load the VBIOS. Is there any way I can fix the error?

```
Read ROM file /Users/sakthi/Downloads/HP.QuadroK2100M.2048.130612.rom, which is 100864 bytes long
DCB header is at 0xffff with length 0x52
DCB Version 5.3
Unknown version
Invalid DCB Signature
Press the enter key to continue...
```

Thanks!

**Comment by averycblack** [comment]
K2100M is Kepler, which is known to not work with this tool. I don't know where the DCB table is in newer VBIOSes.
