### ISSUE TITLE
Invalid DCB Signature

### ISSUE THREAD

**Issue by time-spacex** [1Revenger1/NVCAP-Calculator#9]
Hi, can you tell me please, is there any solution?
palit gtx 1060 3 gb, bios link - https://www.techpowerup.com/vgabios/?architecture=&manufacturer=Palit&model=GTX+1060+3GB&version=&interface=&memType=&memSize=3072&since=
I tried both, I get the following:
Read ROM file /Users/user/Palit.GTX10603GB.3072.170818.rom, which is 258560 bytes long
DCB header is at 0x0 with length 0x56
DCB Version 4.14
Unknown version
Invalid DCB Signature
Press the enter key to continue...

**Comment by averycblack** [comment]
Afaik, you don't really need to bother with nvcap on 700, 900, and 1000 series cards.
This tool only supports 400 series cards and older.
